# Generated by Django 2.0 on 2018-08-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productrecord',
            table='product_records',
        ),
    ]
