#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

services:
  worker_test:
    build: .
    env_file: test_common.env
    command: /project/operation_log/test_celery.sh

  worker_proc:
    build: .
    env_file: proc_common.env
    command: /project/operation_log/proc_celery.sh
