# Generated by Django 2.0.7 on 2018-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='文件名称', max_length=100, verbose_name='文件名称')),
                ('status', models.CharField(help_text='状态', max_length=20, verbose_name='状态')),
                ('operator', models.IntegerField(default=0, help_text='创建人', verbose_name='创建人')),
                ('operator_name', models.CharField(help_text='创建人用户名', max_length=100, verbose_name='创建人用户名')),
                ('download_url', models.URLField(help_text='下载url', max_length=1000, verbose_name='下载url')),
                ('extras', models.CharField(blank=True, help_text='其他参数', max_length=500, null=True, verbose_name='其他参数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='文件名称', max_length=100, verbose_name='文件名称')),
                ('status', models.CharField(help_text='状态', max_length=20, verbose_name='状态')),
                ('success_count', models.IntegerField(help_text='上传成功条数', verbose_name='上传成功条数')),
                ('failed_count', models.IntegerField(default=0, help_text='上传失败条数', verbose_name='上传失败条数')),
                ('operator', models.IntegerField(default=0, help_text='创建人', verbose_name='创建人')),
                ('operator_name', models.CharField(help_text='创建人用户名', max_length=100, verbose_name='创建人用户名')),
                ('file_url', models.URLField(blank=True, help_text='文件url', max_length=1000, null=True, verbose_name='文件url')),
                ('extras', models.CharField(blank=True, help_text='其他参数', max_length=500, null=True, verbose_name='其他参数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
